[package]
name = "ml_dsa_bug"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3 = "1.5.5"
ml-dsa = { git = "https://github.com/RustCrypto/signatures.git", version = "0.1.0-pre.2" }
hybrid-array = { version = "0.3.0", features = ["extra-sizes"] }

[profile.dev]
opt-level = 2
